version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: vyntech_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: VynTech2024
      POSTGRES_DB: vyntech
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Separate DB for Strapi CMS (do not share with Next.js Prisma DB)
  strapi_db:
    image: postgres:16-alpine
    container_name: vyntech_strapi_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: VynTech2024
      POSTGRES_DB: vyntech_strapi
    ports:
      - "5437:5432"
    volumes:
      - strapi_postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  strapi_postgres_data:
