-- Drop legacy Next.js SEO panel tables (live SEO is Strapi-only).

DROP TABLE IF EXISTS "SeoRankHistory" CASCADE;
DROP TABLE IF EXISTS "SeoKeyword" CASCADE;
DROP TABLE IF EXISTS "SeoSession" CASCADE;
DROP TABLE IF EXISTS "SeoPage" CASCADE;
DROP TABLE IF EXISTS "SeoBacklink" CASCADE;
DROP TABLE IF EXISTS "SeoTask" CASCADE;
DROP TABLE IF EXISTS "SeoAudit" CASCADE;
DROP TABLE IF EXISTS "SeoCompetitor" CASCADE;
DROP TABLE IF EXISTS "SeoTechnicalIssue" CASCADE;
DROP TABLE IF EXISTS "SeoContentBrief" CASCADE;
DROP TABLE IF EXISTS "SeoReport" CASCADE;
DROP TABLE IF EXISTS "SeoSettings" CASCADE;
DROP TABLE IF EXISTS "SeoActivityLog" CASCADE;
