export const SITE_URL = "https://weborbitztech.ca";

export const DEFAULT_SITE_PAGES = [
  { path: "/", title: "WebOrbitz | Building Digital Excellence for Canadian Businesses", focusKeyword: "web development Canada" },
  { path: "/about", title: "About Us - Our Story & Mission", focusKeyword: "digital agency Canada" },
  { path: "/services", title: "Our Services - Web Development, Mobile Apps & More", focusKeyword: "web development services Canada" },
  { path: "/services/web-development", title: "Web Development Services", focusKeyword: "custom web development Canada" },
  { path: "/services/mobile-app-development", title: "Mobile App Development", focusKeyword: "mobile app development Canada" },
  { path: "/services/cloud-solutions", title: "Cloud Solutions", focusKeyword: "cloud solutions Canada" },
  { path: "/services/ai-ml-solutions", title: "AI/ML Solutions", focusKeyword: "AI development Canada" },
  { path: "/services/devops-cicd", title: "DevOps & CI/CD", focusKeyword: "DevOps services Canada" },
  { path: "/services/ui-ux-design", title: "UI/UX Design", focusKeyword: "UI UX design agency Canada" },
  { path: "/services/ecommerce-solutions", title: "E-commerce Solutions", focusKeyword: "ecommerce development Canada" },
  { path: "/services/custom-software-development", title: "Custom Software Development", focusKeyword: "custom software Canada" },
  { path: "/services/seo-digital-marketing", title: "SEO/Digital Marketing", focusKeyword: "SEO services Canada" },
  { path: "/services/maintenance-support", title: "Maintenance & Support", focusKeyword: "website maintenance Canada" },
  { path: "/services/tax-accounting", title: "Tax & Accounting Services", focusKeyword: "tax accounting software Canada" },
  { path: "/industries", title: "Industries We Serve", focusKeyword: "industry software solutions" },
  { path: "/industries/healthcare", title: "Healthcare Digital Solutions", focusKeyword: "healthcare software Canada" },
  { path: "/industries/finance-banking", title: "Fintech Solutions", focusKeyword: "fintech development Canada" },
  { path: "/industries/ecommerce-retail", title: "E-commerce & Retail Solutions", focusKeyword: "retail ecommerce Canada" },
  { path: "/industries/education", title: "Education Technology Solutions", focusKeyword: "edtech development Canada" },
  { path: "/industries/real-estate", title: "Real Estate Digital Solutions", focusKeyword: "real estate software Canada" },
  { path: "/industries/logistics", title: "Logistics & Supply Chain Solutions", focusKeyword: "logistics software Canada" },
  { path: "/industries/entertainment-media", title: "Entertainment & Media Solutions", focusKeyword: "media app development Canada" },
  { path: "/industries/manufacturing", title: "Manufacturing Software Solutions", focusKeyword: "manufacturing software Canada" },
  { path: "/industries/hospitality-travel", title: "Hospitality & Travel Solutions", focusKeyword: "hospitality software Canada" },
  { path: "/industries/telecommunications", title: "Telecommunications Solutions", focusKeyword: "telecom software Canada" },
  { path: "/blog", title: "Blog - Insights & Industry Trends", focusKeyword: "web development blog" },
  { path: "/blog/why-custom-software-beats-off-the-shelf", title: "Why Custom Software Beats Off-the-Shelf", focusKeyword: "custom software development" },
  { path: "/blog/web-app-vs-mobile-app-which-to-build-first", title: "Web App vs Mobile App", focusKeyword: "web app vs mobile app" },
  { path: "/blog/how-to-choose-tech-stack-for-startup", title: "How to Choose Tech Stack for Startup", focusKeyword: "tech stack startup" },
  { path: "/blog/mvp-development-how-long-and-how-much", title: "MVP Development Guide", focusKeyword: "MVP development cost" },
  { path: "/blog/api-integration-guide-for-business-owners", title: "API Integration Guide", focusKeyword: "API integration business" },
  { path: "/blog/website-redesign-checklist-2024", title: "Website Redesign Checklist", focusKeyword: "website redesign checklist" },
  { path: "/careers", title: "Careers - Join Our Team", focusKeyword: "tech jobs Canada" },
  { path: "/lets-talk-business", title: "Contact Us - Let's Build Together", focusKeyword: "web development quote Canada" },
  { path: "/privacy-policy", title: "Privacy Policy", focusKeyword: "" },
  { path: "/terms-and-conditions", title: "Terms and Conditions", focusKeyword: "" },
];

export const DEFAULT_TECHNICAL_CHECKS = [
  { title: "XML Sitemap submitted to Google Search Console", category: "crawlability", severity: "high" },
  { title: "Robots.txt configured correctly", category: "crawlability", severity: "high" },
  { title: "HTTPS enabled site-wide", category: "security", severity: "critical" },
  { title: "Mobile-friendly responsive design", category: "mobile", severity: "critical" },
  { title: "Core Web Vitals passing (LCP, FID, CLS)", category: "performance", severity: "high" },
  { title: "Structured data (Schema.org) implemented", category: "structured-data", severity: "medium" },
  { title: "Canonical tags on all pages", category: "on-page", severity: "medium" },
  { title: "Image alt attributes optimized", category: "on-page", severity: "medium" },
  { title: "Internal linking structure optimized", category: "on-page", severity: "medium" },
  { title: "404 pages handled with custom page", category: "crawlability", severity: "low" },
];

export const SEO_PANEL_SECTIONS = [
  { id: "dashboard", label: "Dashboard", icon: "📊" },
  { id: "keywords", label: "Keywords", icon: "🔑" },
  { id: "pages", label: "On-Page SEO", icon: "📄" },
  { id: "technical", label: "Technical SEO", icon: "⚙️" },
  { id: "backlinks", label: "Backlinks", icon: "🔗" },
  { id: "content", label: "Content", icon: "✍️" },
  { id: "competitors", label: "Competitors", icon: "🎯" },
  { id: "tasks", label: "Tasks", icon: "✅" },
  { id: "audits", label: "Audits", icon: "🔍" },
  { id: "reports", label: "Reports", icon: "📈" },
  { id: "analytics", label: "Analytics", icon: "📉" },
  { id: "settings", label: "Settings", icon: "⚡" },
] as const;

export type SeoSectionId = (typeof SEO_PANEL_SECTIONS)[number]["id"];
